cmake_minimum_required(VERSION 3.12)

function(Rxt_emscripten_link_boost _TARGET)
    if(DISABLE_BOOST)
        message(SEND_ERROR "Target ${_TARGET} requires Boost, but it is disabled")
    endif()
    if(EMSCRIPTEN)
        target_link_options(${_TARGET} PUBLIC "SHELL:-s USE_BOOST_HEADERS=1")
    else()
        find_package(Boost 1.68 REQUIRED ${ARGN})
        list(TRANSFORM ARGN PREPEND "Boost::")
        target_link_libraries(${_TARGET} PUBLIC ${ARGN})
    endif()
endfunction()
